use_frameworks!

platform :ios, '10.0'

target 'CocopodsPodTest_Example' do
  pod 'CocopodsPodTest', :path => '../'

  target 'CocopodsPodTest_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
